version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-list2-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    # volumes:
    #   - ./server:/usr/src/server
    #   - ./ui:/usr/src/ui
    # command: ["node", "index.js"]

  db:
    image: postgres:15
    container_name: todo-list2-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mkkilkgmom
      POSTGRES_DB: todo_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
